[setup]
statement_files = ["../sql/uservisits.sql"]
statements = [
    "copy uservisits from 's3://crate.amplab/data/1node/uservisits/part-0000*' with (compression = 'gzip')",
    "refresh table uservisits"
]

[[queries]]
statement = '''select hyperloglog_distinct("cCode") from uservisits'''
iterations = 50

[[queries]]
statement = '''select hyperloglog_distinct("visitDate") from uservisits'''
iterations = 50

[teardown]
statements = ["drop table uservisits"]
